- hosts: all
  become: true
  tasks:
      - name: to create group
        group:
         name: engr
         state: present

- hosts: all
  become: true
  tasks:
      - name: to create group
        group:
         name: ednawey
         state: present

- hosts: all
  become: true
  tasks:
      - name: to create group
        group:
         name: research
         state: present

- hosts: all
  become: true
  tasks:
      - name: to create group
        group:
         name: splunk
         state: present


- hosts: all
  become: true
  vars_files:
      - /etc/ansible/vars.yml
  tasks:
      - name: To add several Linux users
        user:
         name: "{{ item.name }}"
         uid: "{{ item.uid }}"
         groups: "{{ item.groups }}"
         password: "{{ item.password }}"
         comment: "{{ item.comment }}"
         shell: "{{ item.shell }}"
         state: present
        with_items: "{{ user_details }}"
